export const CHECKLIST_EQUIPMENT = [
  { itemNumber: 1, equipmentName: "Aferição Bico 1", type: "afericao" },
  { itemNumber: 2, equipmentName: "Aferição Bico 2", type: "afericao" },
  { itemNumber: 3, equipmentName: "Aferição Bico 3", type: "afericao" },
  { itemNumber: 4, equipmentName: "Aferição Bico 4", type: "afericao" },
  { itemNumber: 5, equipmentName: "Aferição Bico Arla", type: "afericao" },
  { itemNumber: 6, equipmentName: "Encerrante Bico 1", type: "encerrante" },
  { itemNumber: 7, equipmentName: "Encerrante Bico 2", type: "encerrante" },
  { itemNumber: 8, equipmentName: "Encerrante Bico 3", type: "encerrante" },
  { itemNumber: 9, equipmentName: "Encerrante Bico 4", type: "encerrante" },
  { itemNumber: 10, equipmentName: "Encerrante Bico Arla", type: "encerrante" },
  { itemNumber: 11, equipmentName: "Bomba Sub. Dispenser 1", type: "equipamento" },
  { itemNumber: 12, equipmentName: "Bomba Sub. Dispenser 2", type: "equipamento" },
  { itemNumber: 13, equipmentName: "Bomba Sub. Dispenser 3", type: "equipamento" },
  { itemNumber: 14, equipmentName: "Bomba Submersa Arla", type: "equipamento" },
  { itemNumber: 15, equipmentName: "Canaleta dos tanques e Spill", type: "equipamento" },
  { itemNumber: 16, equipmentName: "Caixa separadora estacionamento", type: "equipamento" },
  { itemNumber: 17, equipmentName: "Caixa separadora pista abastecimento", type: "equipamento" },
  { itemNumber: 18, equipmentName: "Dispenser 1", type: "equipamento" },
  { itemNumber: 19, equipmentName: "Dispenser 1 Bico 1 Diesel", type: "equipamento" },
  { itemNumber: 20, equipmentName: "Dispenser 1 Bico 2 Diesel", type: "equipamento" },
  { itemNumber: 21, equipmentName: "Dispenser 2 Arla Bico 3", type: "equipamento" },
  { itemNumber: 22, equipmentName: "Dispenser 3", type: "equipamento" },
  { itemNumber: 23, equipmentName: "Dispenser 3 Bico 4 Gasolina", type: "equipamento" },
  { itemNumber: 24, equipmentName: "Dispenser 3 Bico 5 Gasolina", type: "equipamento" },
  { itemNumber: 25, equipmentName: "Elemento Filtrante Diesel", type: "equipamento" },
  { itemNumber: 26, equipmentName: "Mangueira Bico 1 Diesel", type: "equipamento" },
  { itemNumber: 27, equipmentName: "Mangueira Bico 2 Diesel", type: "equipamento" },
  { itemNumber: 28, equipmentName: "Mangueira Bico 3 Arla", type: "equipamento" },
  { itemNumber: 29, equipmentName: "Mangueira Bico 4 Gasolina", type: "equipamento" },
  { itemNumber: 30, equipmentName: "Mangueira Bico 5 Gasolina", type: "equipamento" },
  { itemNumber: 31, equipmentName: "Manômetro Filtro Diesel", type: "equipamento" },
  { itemNumber: 32, equipmentName: "Painel Comando – IHM", type: "equipamento" },
  { itemNumber: 33, equipmentName: "Sensor Inter. Tanque 1", type: "equipamento" },
  { itemNumber: 34, equipmentName: "Sensor Inter. Tanque 2 e 3", type: "equipamento" },
  { itemNumber: 35, equipmentName: "Sensor Interrompe sistema", type: "equipamento" },
  { itemNumber: 36, equipmentName: "Sensor Sump Caixa Transição 1", type: "equipamento" },
  { itemNumber: 37, equipmentName: "Sensor Sump Caixa Transição 2", type: "equipamento" },
  { itemNumber: 38, equipmentName: "Sensor Sump Dispenser 1", type: "equipamento" },
  { itemNumber: 39, equipmentName: "Sensor Sump Dispenser 2", type: "equipamento" },
  { itemNumber: 40, equipmentName: "Sensor Sump Dispenser Arla", type: "equipamento" },
  { itemNumber: 41, equipmentName: "Sensor Sump Tanque 1", type: "equipamento" },
  { itemNumber: 42, equipmentName: "Sensor Sump Tanque 2", type: "equipamento" },
  { itemNumber: 43, equipmentName: "Sensor Sump Tanque 3", type: "equipamento" },
  { itemNumber: 44, equipmentName: "Spill Container Abastecimento Tanque 1", type: "equipamento" },
  { itemNumber: 45, equipmentName: "Spill Container Abastecimento Tanque 2", type: "equipamento" },
  { itemNumber: 46, equipmentName: "Spill Container Abastecimento Tanque 3", type: "equipamento" },
  { itemNumber: 47, equipmentName: "Spill Container Medição Tanque 1", type: "equipamento" },
  { itemNumber: 48, equipmentName: "Spill Container Medição Tanque 2", type: "equipamento" },
  { itemNumber: 49, equipmentName: "Spill Container Medição Tanque 3", type: "equipamento" },
  { itemNumber: 50, equipmentName: "Sump Caixa Transição 1", type: "equipamento" },
  { itemNumber: 51, equipmentName: "Sump Caixa Transição 2", type: "equipamento" },
  { itemNumber: 52, equipmentName: "Sump Dispenser 1 Diesel", type: "equipamento" },
  { itemNumber: 53, equipmentName: "Sump Dispenser 2 Arla", type: "equipamento" },
  { itemNumber: 54, equipmentName: "Sump Dispenser 3 Gasolina", type: "equipamento" },
  { itemNumber: 55, equipmentName: "Sump Tanque 1", type: "equipamento" },
  { itemNumber: 56, equipmentName: "Sump Tanque 2", type: "equipamento" },
  { itemNumber: 57, equipmentName: "Sump Tanque 3", type: "equipamento" },
  { itemNumber: 58, equipmentName: "Swivel Bico 1", type: "equipamento" },
  { itemNumber: 59, equipmentName: "Swivel Bico 2", type: "equipamento" },
  { itemNumber: 60, equipmentName: "Swivel Bico 3 Arla", type: "equipamento" },
  { itemNumber: 61, equipmentName: "Swivel Bico 4", type: "equipamento" },
  { itemNumber: 62, equipmentName: "Swivel Bico 5", type: "equipamento" },
  { itemNumber: 63, equipmentName: "Boca de Descarga à distância", type: "equipamento" },
  { itemNumber: 64, equipmentName: "Veeder-Root", type: "equipamento" },
] as const;

export type ChecklistEquipmentType = "afericao" | "encerrante" | "equipamento";
